apiVersion: apps/v1
kind: Deployment
metadata:
  name: equities-bot
  namespace: trading
spec:
  replicas: 1
  selector:
    matchLabels:
      app: equities-bot
  template:
    metadata:
      labels:
        app: equities-bot
    spec:
      containers:
      - name: equities-container
        image: alex2938e2/trading-bot:latest
        imagePullPolicy: Always
        command: ["python", "bot_intraday_etfs.py"]
        envFrom:
        - secretRef:
            name: bot-secrets
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: hardware
                operator: In
                values:
                - hp-t630
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: commodities-bot
  namespace: trading
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commodities-bot
  template:
    metadata:
      labels:
        app: commodities-bot
    spec:
      containers:
      - name: commodities-container
        image: alex2938e2/trading-bot:latest
        imagePullPolicy: Always
        command: ["python", "bot_swing_commodities.py"]
        envFrom:
        - secretRef:
            name: bot-secrets
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: hardware
                operator: In
                values:
                - hp-t630
